import { useMemo, useState } from "react";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { apiRequest } from "../src/api/client";
import type { Household, KycResponse } from "../src/api/types";
import { getStrings } from "../src/i18n";
import type { Language } from "../src/i18n/translations";
import { theme } from "../src/theme";

type Step="language"|"ration"|"member"|"consent"|"processing"|"success";
export default function HomeScreen(){
 const [language,setLanguage]=useState<Language>("en"),[step,setStep]=useState<Step>("language"),[rationCard,setRationCard]=useState(""),[household,setHousehold]=useState<Household|null>(null),[selected,setSelected]=useState(""),[consented,setConsented]=useState(false),[reference,setReference]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const s=useMemo(()=>getStrings(language),[language]);
 async function lookup(){setError("");setLoading(true);try{const h=await apiRequest<Household>("/v1/households/"+encodeURIComponent(rationCard.trim()));setHousehold(h);setStep("member")}catch{setError(s.error)}finally{setLoading(false)}}
 async function start(){if(!consented||!household||!selected)return;setError("");setLoading(true);setStep("processing");try{const response=await apiRequest<KycResponse>("/v1/kyc",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({householdReference:household.householdReference,memberReference:selected,consentReference:"citizen-consent"})});setReference(response.requestId);setStep("success")}catch{setStep("consent");setError(s.error)}finally{setLoading(false)}}
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
 <View style={styles.header}><View style={styles.logo}><Text style={styles.logoText}>N</Text></View><View style={{flex:1}}><Text style={styles.title}>{s.appName}</Text><Text style={styles.subtitle}>{s.tagline}</Text></View></View>
 {step!=="language"&&<View style={styles.progress}><View style={[styles.progressFill,{width:step==="success"?"100%":step==="processing"?"85%":step==="consent"?"68%":step==="member"?"50%":"28%"}]}/></View>}
 {step==="language"&&<Card><Text style={styles.heading}>{s.chooseLanguage}</Text><Text style={styles.muted}>{s.languageHint}</Text><LanguageButton label={s.english} selected={language==="en"} onPress={()=>setLanguage("en")}/><LanguageButton label={s.kannada} selected={language==="kn"} onPress={()=>setLanguage("kn")}/><Primary label={s.continue} onPress={()=>setStep("ration")}/></Card>}
 {step==="ration"&&<Card><Text style={styles.heading}>{s.rationCard}</Text><Text style={styles.muted}>{s.rationCardHint}</Text><TextInput value={rationCard} onChangeText={setRationCard} autoCapitalize="characters" placeholder={s.rationCard} style={styles.input}/><Primary label={loading?s.processing:s.findHousehold} onPress={lookup} disabled={!rationCard.trim()||loading}/></Card>}
 {step==="member"&&household&&<Card><Text style={styles.heading}>{s.household}</Text><Text style={styles.muted}>{s.selectMember}</Text>{household.members.map(m=><Pressable key={m.memberReference} onPress={()=>{setSelected(m.memberReference);setStep("consent")}} style={styles.member}><View style={{flex:1}}><Text style={styles.memberName}>{m.displayName}</Text><Text style={styles.muted}>{m.kycRequired?s.kycRequired:s.kycComplete}</Text></View><Text style={styles.arrow}>›</Text></Pressable>)}</Card>}
 {step==="consent"&&<Card><Text style={styles.heading}>{s.consent}</Text><Pressable onPress={()=>setConsented(!consented)} style={styles.consent}><Text style={styles.check}>{consented?"✓":"○"}</Text><Text style={styles.body}>{s.consentText}</Text></Pressable><Text style={styles.muted}>{s.privacyText}</Text><Primary label={s.startVerification} onPress={start} disabled={!selected||!consented||loading}/></Card>}
 {step==="processing"&&<Card><Text style={styles.heading}>{s.processing}</Text><Text style={styles.muted}>{s.processingText}</Text><View style={styles.loader}/></Card>}
 {step==="success"&&<Card><Text style={styles.success}>✓</Text><Text style={styles.heading}>{s.success}</Text><Text style={styles.body}>{s.successText}</Text><Text style={styles.reference}>{s.reference}: {reference}</Text></Card>}
 {error?<Text style={styles.error}>{error}</Text>:null}
 {step!=="language"&&step!=="success"&&<Pressable onPress={()=>setStep(step==="ration"?"language":step==="member"?"ration":"member")}><Text style={styles.back}>{s.back}</Text></Pressable>}
 <Text style={styles.footer}>{s.demoNote}</Text>
 </ScrollView></SafeAreaView>;
}
function Card({children}:{children:React.ReactNode}){return <View style={styles.card}>{children}</View>}
function Primary({label,onPress,disabled}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.primary,disabled&&styles.disabled]}><Text style={styles.primaryText}>{label}</Text></Pressable>}
function LanguageButton({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.language,selected&&styles.languageSelected]}><Text style={styles.languageText}>{label}</Text>{selected&&<Text style={styles.tick}>✓</Text>}</Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},container:{padding:24,paddingTop:32,gap:18},header:{flexDirection:"row",alignItems:"center",gap:12},logo:{width:50,height:50,borderRadius:16,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center"},logoText:{color:"#fff",fontSize:28,fontWeight:"800"},title:{fontSize:27,fontWeight:"800",color:theme.colors.text},subtitle:{fontSize:14,color:theme.colors.muted,marginTop:2},progress:{height:5,borderRadius:4,backgroundColor:theme.colors.border,overflow:"hidden"},progressFill:{height:"100%",backgroundColor:theme.colors.primary},card:{backgroundColor:theme.colors.surface,borderRadius:theme.radius.card,padding:theme.spacing.lg,borderWidth:1,borderColor:theme.colors.border,gap:14},heading:{fontSize:22,fontWeight:"800",color:theme.colors.text},muted:{fontSize:14,color:theme.colors.muted,lineHeight:21},body:{fontSize:16,color:theme.colors.text,lineHeight:24},language:{minHeight:58,paddingHorizontal:18,borderRadius:theme.radius.input,borderWidth:1,borderColor:theme.colors.border,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},languageSelected:{borderColor:theme.colors.primary,backgroundColor:"#EEF7F1",borderWidth:2},languageText:{fontSize:17,fontWeight:"700",color:theme.colors.text},tick:{fontSize:20,color:theme.colors.primary},primary:{minHeight:54,padding:16,borderRadius:theme.radius.button,backgroundColor:theme.colors.primary,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontSize:16,fontWeight:"800"},disabled:{opacity:.45},input:{minHeight:54,padding:15,borderRadius:theme.radius.input,borderWidth:1,borderColor:theme.colors.border,fontSize:17,color:theme.colors.text,backgroundColor:"#fff"},member:{minHeight:72,padding:16,borderRadius:14,borderWidth:1,borderColor:theme.colors.border,flexDirection:"row",alignItems:"center"},memberName:{fontSize:17,fontWeight:"700",color:theme.colors.text},arrow:{fontSize:30,color:theme.colors.primary},consent:{flexDirection:"row",gap:10,alignItems:"flex-start"},check:{fontSize:26,color:theme.colors.primary},success:{fontSize:50,color:theme.colors.success,fontWeight:"800"},reference:{fontSize:13,color:theme.colors.muted},loader:{height:5,borderRadius:3,backgroundColor:theme.colors.primary,width:"55%"},back:{textAlign:"center",fontSize:15,fontWeight:"700",color:theme.colors.primary},footer:{textAlign:"center",fontSize:12,color:theme.colors.muted,paddingVertical:8},error:{color:theme.colors.error,fontSize:14}});
